package com.telusko;

/**
 * This class represents the structure of the response that will be sent back to the client.
 * It's a simplified wrapper around the content returned by the AI model.
 */
public class ChatResponse {
    // The text content generated by the AI model
    private String content;

    public ChatResponse(String content) {
        this.content = content;
    }


    public String getContent() {
        return content;
    }


    public void setContent(String content) {
        this.content = content;
    }
}
